name: egaznepy_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mamba
  - python<3.10
  - jupyter
  - matplotlib
  - seaborn
  - typer
  - pre-commit
  - pyupgrade
  - pytest
  - isort
  - black
