name: egaznepy_dev
channels:
  - conda-forge
dependencies:
  - mamba
  - python<3.10
  - typer
  - pre-commit
  - pyupgrade
  - pytest
  - isort
  - black
  - darglint
  - coverage
  - coverage-badge
  - pytest-cov
  - pytest-html
  - mypy
  - pip
  - pydocstyle
  - safety
  - bandit
