name: egaznepy_dev
channels:
  - conda-forge
dependencies:
  - mamba
  - python>=3.9
  - matplotlib
  - seaborn
  - IPython
  # development prequisites
  - typer
  - pre-commit
  - pyupgrade
  - pytest
  - isort
  - black
  - darglint
  - coverage
  - coverage-badge
  - pytest-cov
  - pytest-html
  - mypy
  - pip
  - pydocstyle
  - safety
  - bandit
  - pip:
    - -e .
