name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Miniconda
    - uses: conda-incubator/setup-miniconda@v2
      run: |
        conda install mamba

    - name: Install dependencies
      run: |
        make install
        conda activate egaznepy_dev/

    - name: Run style checks
      run: |
        make check-codestyle

    - name: Run tests
      run: |
        make test

    - name: Run safety checks
      run: |
        make check-safety
